baseURL = "https://bytes.xerolinux.xyz"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "DarkXero Bytes"
theme = "anubis2"

[pagination]
pagerSize = 5

[params.author]
name = "DarkXero"
email  = "info@techxero.com"
location = "Lebanon"

[params]
description = "Home of a FOSS Maintainer"
dateFormat = "2006-01-02"
paginationSinglePost = true

locale = "en-us"

[params.anubis2]
    tocWordCount = true
    enableRssIcon = true
    readNextPosts = 2
    openInNewTab = true
    enableCopyCodeButton = true
    enableReadMoreButton = true
    hideFooterAttribution = false # hide "Powered by Hugo, theme" in footer
    colorTheme = "dark"
    enableColorThemeSwitcher = false

    social = [
        { id = "github", url = "https://github.com/DarkXero-dev" },
        { id = "linkedin", url = "https://www.linkedin.com/in/schaanine/" },
        { id = "email", url = "info@techxero.com.com" },
        { id = "youtube", url = "https://www.youtube.com/@TechXeroLB" },
    ]


    [params.anubis2.services]
        [params.anubis2.services.giscus]
            # Giscus Comment System https://giscus.app/
            repo        = "xerolinux/XeroSite"
            repoId      = "R_kgDOMmVchg"
            category    = "General"
            categoryId  = "DIC_kwDOMmVchs4Cs7z_"
            dataMapping = "pathname"
            lazyLoad    = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "guides"
name = "Guides"
url = "/guides/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'dracula' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 6
