site_name: DarkXero's Journal
site_description: Personal Thoughts, Documentation, and more...
site_url: https://blog.xerolinux.xyz

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple

plugins:
  - search
  - autorefs
  - htmlproofer
  - glightbox
  - redirects
  - ezlinks
  # - rss:
  #     categories:
  #       - tags
  #     date_from_meta:
  #       as_creation: "date" # means from page.meta.date
  #       as_update: "git" # means from git log
  #       datetime_format: "%Y-%m-%d %H:%M"
  #       default_time: "09:30"
  #       default_timezone: Asia/Beirut
  #     enabled: true
  #     feeds_filenames:
  #       json_created: feed_json_created.json
  #       json_updated: feed_json_updated.json
  #       rss_created: feed_rss_created.xml
  #       rss_updated: feed_rss_updated.xml
  #     feed_ttl: 1440
  #     image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
  #     json_feed_enabled: true
  #     length: 20
  #     match_path: ".*"
  #     pretty_print: false
  #     rss_feed_enabled: true
  #     url_parameters:
  #       utm_source: "documentation"
  #       utm_medium: "RSS"
  #       utm_campaign: "feed-syndication"
  #     use_git: true
  #     use_material_social_cards: true
